Document: amxa-bootserver-extra
Title: Debian amxa-bootserver-extra Manual
Author: <insert document author here>
Abstract: This manual describes what amxa-bootserver-extra is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/amxa-bootserver-extra/amxa-bootserver-extra.sgml.gz

Format: postscript
Files: /usr/share/doc/amxa-bootserver-extra/amxa-bootserver-extra.ps.gz

Format: text
Files: /usr/share/doc/amxa-bootserver-extra/amxa-bootserver-extra.text.gz

Format: HTML
Index: /usr/share/doc/amxa-bootserver-extra/html/index.html
Files: /usr/share/doc/amxa-bootserver-extra/html/*.html
